# This file is for Render.com deployment only. You can safely delete it if switching to Railway.
# services:
#   - type: web
#     name: nbkrist-student-portal
#     env: python
#     buildCommand: "./render-build.sh"
#     startCommand: "python -m playwright install chromium && gunicorn app:app --bind 0.0.0.0:10000"
#     plan: free
#     envVars:
#       - key: PYTHON_VERSION
#         value: 3.9.0
