services:
  # Web service for the Flask application
  - type: web
    name: nbkrist-student-portal
    env: python
    buildCommand: |
      # Install Chrome for web scraping
      apt-get update
      apt-get install -y wget gnupg
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update
      apt-get install -y google-chrome-stable
      # Install Python dependencies
      pip install -r requirements.txt
      # Install Playwright with all dependencies
      pip install playwright
      python -m playwright install --with-deps chromium
      # Verify installation
      python -c "from playwright.sync_api import sync_playwright; print('Playwright installation verified')"
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: student-details
      - key: RENDER
        value: "true"
    healthCheckPath: /
    # Free instance type
    plan: free
    disk:
      name: student-data
      mountPath: /tmp/student_details
      sizeGB: 1

# Specify Python version
buildEnv:
  PYTHON_VERSION: 3.9.0
